# Generated by Django 3.0.5 on 2020-08-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200822_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_at']},
        ),
    ]
