# Generated by Django 3.0.5 on 2020-07-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followee', 'follower')},
        ),
    ]
