# Generated by Django 3.0.5 on 2020-04-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Stream'),
        ),
    ]
