# Generated by Django 3.0.5 on 2020-04-16 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20200416_1759'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follows', '0002_follow_stream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('account', 'stream', 'stream_follows_account')},
        ),
    ]
