# Generated by Django 3.0.5 on 2020-07-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20200720_2219'),
        ('follows', '0002_auto_20200720_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='streams',
            field=models.ManyToManyField(blank=True, related_name='follows', to='streams.Stream'),
        ),
    ]
