# Generated by Django 3.0.5 on 2020-07-22 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_follows'),
        ('streams', '0002_auto_20200720_2219'),
        ('follows', '0003_follow_streams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Stream')),
            ],
            options={
                'unique_together': {('profile', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='StreamFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Stream')),
            ],
            options={
                'unique_together': {('profile', 'stream')},
            },
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
