# Generated by Django 3.0.5 on 2020-07-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0004_auto_20200722_1341'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profilefollow',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('stream', 'profile'), name='unique_field_profile_stream'),
        ),
    ]
