# Generated by Django 3.0.5 on 2020-07-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0005_auto_20200725_2047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilefollow',
            unique_together=set(),
        ),
    ]
