# Generated by Django 3.0.5 on 2020-04-16 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_follow_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0003_auto_20200416_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='accounts',
            field=models.ManyToManyField(related_name='streams', through='follows.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
