# Generated by Django 3.0.5 on 2020-04-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_stream_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='accounts',
            new_name='account',
        ),
    ]
