# Generated by Django 3.0.5 on 2020-08-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        ('follows', '0002_auto_20200816_1942'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_streams',
            field=models.ManyToManyField(related_name='following_profiles', through='follows.StreamFollow', to='streams.Stream'),
        ),
    ]
