# Generated by Django 3.0.5 on 2020-08-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_followed_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
