# Generated by Django 3.0.5 on 2020-07-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200718_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followerCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='followingCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_stream',
            field=models.IntegerField(default=0),
        ),
    ]
