# Generated by Django 3.0.5 on 2020-07-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200720_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followerCount',
            new_name='follower_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='followingCount',
            new_name='following_count',
        ),
    ]
