# Generated by Django 3.0.5 on 2020-08-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200816_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_stream',
        ),
    ]
