# Generated by Django 3.0.5 on 2020-08-24 22:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200816_2341'),
        ('profiles', '0004_remove_profile_last_stream'),
        ('likes', '0003_auto_20200822_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('owner', 'post'), name='unique_post_like'),
        ),
    ]
